
BLOCO_LARGURA = 50
BLOCO_ALTURA = 50
COLUNAS= 10
LINHAS = 8


RESOLUCAO = LARGURA, ALTURA =  int(BLOCO_LARGURA * COLUNAS) , int(BLOCO_ALTURA * LINHAS)
FPS = 62


PLAYER_LARGURA = 50 
PLAYER_ALTURA  = 50

PLAYER_POS = PLAYER_POS_X, PLAYER_POS_Y = 370, 200
PLAYER_DIM = PLAYER_LARGURA , PLAYER_ALTURA
PLAYER_DRAW = PLAYER_POS, PLAYER_DIM

VELOCIDADE = 10